networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - server
      - client
    networks:
      - dev

    postgres:
      image: postgres:13.3
      environment:
        POSTGRES_DB: "zoo_md"
        POSTGRES_USER: "[postgres]"
        POSTGRES_PASSWORD: "root"
      ports:
        - "5432:5432"

  server:
    build:
      context: ./server
    networks:
      - dev

  client:
    build:
      context: ./client
    networks:
      - dev